services:
  - type: web
    name: i7-game-guide
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # This will be set from Render dashboard or via API